#!/usr/bin/env bash

CONTAINERS_DIR_PATH=~/work/cont;
CONTAINERS_HOST_CONFIG_DIR_PATH=~/.ssh/cnt_cnf;
CONTAINERS_DOMAIN_SUFFIX=mdva.dev
CONTAINERS_IP_TEMPLATE='127.0.NUM1.NUM2'
USE_NETWORK_ALIAS="1"
USE_MAC_SED="1"
CREATE_HOST_CONFIG="1"